using TUnit.Assertions.Core;

namespace TestUtilities.StringAssertions;

/// <summary>
/// A custom TUnit assertion that compares strings with normalized line endings.
/// This is specifically introduced to ease assertions against CSV generated by CsvHelper,
/// which writes CRLF line endings by default following RFC 4180.
/// </summary>
public class StringEqualsWithNormalizedLineEndingsAssertion : Assertion<string>
{
    private readonly string _expected;

    public StringEqualsWithNormalizedLineEndingsAssertion(AssertionContext<string> context, string expected)
        : base(context)
    {
        _expected = expected;
    }

    protected override Task<AssertionResult> CheckAsync(EvaluationMetadata<string> metadata)
    {
        var actual = metadata.Value;
        
        if (actual is null)
        {
            return Task.FromResult(AssertionResult.Failed("Actual string was null"));
        }

        var normalizedActual = actual.ReplaceLineEndings();
        var normalizedExpected = _expected.ReplaceLineEndings();

        if (normalizedActual == normalizedExpected)
        {
            return Task.FromResult(AssertionResult.Passed);
        }

        return Task.FromResult(AssertionResult.Failed(
            $"""
             Strings do not match (ignoring line endings).
             Expected:
             {_expected}
             
             Actual:
             {actual}
             """));
    }

    protected override string GetExpectation()
        => $"to be equal to \"{_expected}\" (ignoring line endings)";
}
