using System.Collections.Immutable;
using System.Text.Json;

namespace EHonda.KicktippAi.Core;

public sealed class ResolvedTypedContextDocument : IEquatable<ResolvedTypedContextDocument>
{
    public ResolvedTypedContextDocument(string kind, string name, int version, string contentSha256) => (Kind, Name, Version, ContentSha256) = (kind, name, version, contentSha256);
    public string Kind { get; } public string Name { get; } public int Version { get; } public string ContentSha256 { get; }
    public bool Equals(ResolvedTypedContextDocument? other) => other is not null && Version == other.Version && Same(Kind, other.Kind) && Same(Name, other.Name) && Same(ContentSha256, other.ContentSha256);
    public override bool Equals(object? obj) => Equals(obj as ResolvedTypedContextDocument);
    public override int GetHashCode() => HashCode.Combine(OrdinalHash(Kind), OrdinalHash(Name), Version, OrdinalHash(ContentSha256));
    private static bool Same(string? x, string? y) => string.Equals(x, y, StringComparison.Ordinal); private static int OrdinalHash(string? value) => StringComparer.Ordinal.GetHashCode(value ?? string.Empty);
}

public sealed class ResolvedTypedContextManifest : IEquatable<ResolvedTypedContextManifest>
{
    private readonly ImmutableArray<ResolvedTypedContextDocument> _documents;
    public ResolvedTypedContextManifest(string seasonPartition, string communityContext, BundesligaSeasonSubcompetition bundesligaSeasonSubcompetition, string profileId, string routingSeedSha256, DateTimeOffset rulesObservedAt, string rulesSchemaVersion, string canonicalRulesSha256, IEnumerable<ResolvedTypedContextDocument> documents)
    { (SeasonPartition, CommunityContext, BundesligaSeasonSubcompetition, ProfileId, RoutingSeedSha256, RulesObservedAt, RulesSchemaVersion, CanonicalRulesSha256) = (seasonPartition, communityContext, bundesligaSeasonSubcompetition, profileId, routingSeedSha256, rulesObservedAt, rulesSchemaVersion, canonicalRulesSha256); _documents = documents?.ToImmutableArray() ?? throw new ArgumentNullException(nameof(documents)); }
    public string SeasonPartition { get; } public string CommunityContext { get; } public BundesligaSeasonSubcompetition BundesligaSeasonSubcompetition { get; } public string ProfileId { get; } public string RoutingSeedSha256 { get; } public DateTimeOffset RulesObservedAt { get; } public string RulesSchemaVersion { get; } public string CanonicalRulesSha256 { get; } public IReadOnlyList<ResolvedTypedContextDocument> Documents => _documents;
    public static ResolvedTypedContextManifest DeserializeCanonical(ReadOnlySpan<byte> bytes) => TypedContextCanonicalJson.DeserializeManifest(bytes);
    public byte[] SerializeCanonical() => TypedContextCanonicalJson.SerializeManifest(this);
    public bool Equals(ResolvedTypedContextManifest? o) => o is not null && RulesObservedAt == o.RulesObservedAt && BundesligaSeasonSubcompetition == o.BundesligaSeasonSubcompetition && Same(SeasonPartition, o.SeasonPartition) && Same(CommunityContext, o.CommunityContext) && Same(ProfileId, o.ProfileId) && Same(RoutingSeedSha256, o.RoutingSeedSha256) && Same(RulesSchemaVersion, o.RulesSchemaVersion) && Same(CanonicalRulesSha256, o.CanonicalRulesSha256) && _documents.SequenceEqual(o._documents);
    public override bool Equals(object? obj) => Equals(obj as ResolvedTypedContextManifest);
    public override int GetHashCode() { var h = new HashCode(); h.Add(SeasonPartition, StringComparer.Ordinal); h.Add(CommunityContext, StringComparer.Ordinal); h.Add(BundesligaSeasonSubcompetition); h.Add(ProfileId, StringComparer.Ordinal); h.Add(RoutingSeedSha256, StringComparer.Ordinal); h.Add(RulesObservedAt); h.Add(RulesSchemaVersion, StringComparer.Ordinal); h.Add(CanonicalRulesSha256, StringComparer.Ordinal); foreach (var d in _documents) h.Add(d); return h.ToHashCode(); }
    private static bool Same(string? x, string? y) => string.Equals(x, y, StringComparison.Ordinal);
}

public sealed record ResolvedTypedContextPublicationBindingKey(string SeasonPartition, string CommunityContext, string ProfileId, string RoutingSeedSha256)
{ public string PhysicalId => TypedContextCanonicalJson.CreatePhysicalBindingId(this); public byte[] CanonicalTupleBytes => TypedContextCanonicalJson.SerializeBindingKeyTuple(this); }

public sealed class ResolvedTypedContextPublicationBinding : IEquatable<ResolvedTypedContextPublicationBinding>
{
    public ResolvedTypedContextPublicationBinding(string seasonPartition, string communityContext, string profileId, string routingSeedSha256, BundesligaSeasonSubcompetition bundesligaSeasonSubcompetition, DateTimeOffset rulesObservedAt, string rulesSchemaVersion, string canonicalRulesSha256, ResolvedTypedContextDocument document)
    { (SeasonPartition, CommunityContext, ProfileId, RoutingSeedSha256, BundesligaSeasonSubcompetition, RulesObservedAt, RulesSchemaVersion, CanonicalRulesSha256, Document) = (seasonPartition, communityContext, profileId, routingSeedSha256, bundesligaSeasonSubcompetition, rulesObservedAt, rulesSchemaVersion, canonicalRulesSha256, document ?? throw new ArgumentNullException(nameof(document))); }
    public string SeasonPartition { get; } public string CommunityContext { get; } public string ProfileId { get; } public string RoutingSeedSha256 { get; } public BundesligaSeasonSubcompetition BundesligaSeasonSubcompetition { get; } public DateTimeOffset RulesObservedAt { get; } public string RulesSchemaVersion { get; } public string CanonicalRulesSha256 { get; } public ResolvedTypedContextDocument Document { get; }
    public ResolvedTypedContextPublicationBindingKey Key => new(SeasonPartition, CommunityContext, ProfileId, RoutingSeedSha256);
    public static ResolvedTypedContextPublicationBinding DeserializeCanonical(ReadOnlySpan<byte> bytes) => TypedContextCanonicalJson.DeserializeBinding(bytes); public byte[] SerializeCanonical() => TypedContextCanonicalJson.SerializeBinding(this);
    public bool Equals(ResolvedTypedContextPublicationBinding? o) => o is not null && RulesObservedAt == o.RulesObservedAt && BundesligaSeasonSubcompetition == o.BundesligaSeasonSubcompetition && Key == o.Key && Document.Equals(o.Document) && Same(RulesSchemaVersion, o.RulesSchemaVersion) && Same(CanonicalRulesSha256, o.CanonicalRulesSha256);
    public override bool Equals(object? obj) => Equals(obj as ResolvedTypedContextPublicationBinding);
    public override int GetHashCode() => HashCode.Combine(Key, BundesligaSeasonSubcompetition, RulesObservedAt, Document, OrdinalHash(RulesSchemaVersion), OrdinalHash(CanonicalRulesSha256));
    private static bool Same(string? x, string? y) => string.Equals(x, y, StringComparison.Ordinal); private static int OrdinalHash(string? value) => StringComparer.Ordinal.GetHashCode(value ?? string.Empty);
}

public static class SchadensfresseTypedContextProfiles
{
    public const string SeasonPartition = CompetitionIds.Bundesliga2026_27, CommunityContext = "schadensfresse", RulesDocumentKind = "Context", RulesDocumentName = "community-rules-schadensfresse.md"; public const int MaximumDocuments = 1, MaximumEstimatedRenderedContextTokens = 2048;
    private static readonly IReadOnlyDictionary<string, BundesligaSeasonSubcompetition> Profiles = new Dictionary<string, BundesligaSeasonSubcompetition>(StringComparer.Ordinal) { ["schadensfresse-dfb-pokal-rules-only-v1"] = BundesligaSeasonSubcompetition.DfbPokal, ["schadensfresse-champions-league-match-rules-only-v1"] = BundesligaSeasonSubcompetition.ChampionsLeague, ["schadensfresse-champions-league-bonus-rules-only-v1"] = BundesligaSeasonSubcompetition.ChampionsLeague };
    public static bool TryGetSubcompetition(string? profile, out BundesligaSeasonSubcompetition value) { value = default; return profile is not null && Profiles.TryGetValue(profile, out value); }
    public static void ValidateManifestStructure(ResolvedTypedContextManifest m, int renderedBytes) { ArgumentNullException.ThrowIfNull(m); ValidateIdentity(m.SeasonPartition, m.CommunityContext, m.ProfileId, m.BundesligaSeasonSubcompetition, m.RoutingSeedSha256, m.RulesSchemaVersion, m.CanonicalRulesSha256); ValidateDocuments(m.Documents, renderedBytes); }
    public static void ValidateManifestFreshness(ResolvedTypedContextManifest m, DateTimeOffset at) { ArgumentNullException.ThrowIfNull(m); TypedContextCanonicalJson.ValidateFreshObservation(m.RulesObservedAt, at); }
    public static void ValidateBindingStructure(ResolvedTypedContextPublicationBinding b) { ArgumentNullException.ThrowIfNull(b); ValidateIdentity(b.SeasonPartition, b.CommunityContext, b.ProfileId, b.BundesligaSeasonSubcompetition, b.RoutingSeedSha256, b.RulesSchemaVersion, b.CanonicalRulesSha256); ValidateDocument(b.Document); }
    public static void ValidateBindingFreshness(ResolvedTypedContextPublicationBinding b, DateTimeOffset at) { ArgumentNullException.ThrowIfNull(b); TypedContextCanonicalJson.ValidateFreshObservation(b.RulesObservedAt, at); }
    internal static void ValidateIdentity(string season, string community, string profile, BundesligaSeasonSubcompetition sub, string seed, string schema, string hash) { if (!string.Equals(season, SeasonPartition, StringComparison.Ordinal) || !string.Equals(community, CommunityContext, StringComparison.Ordinal) || !TryGetSubcompetition(profile, out var expected) || expected != sub || !TypedContextCanonicalJson.IsLowercaseSha256(seed) || !string.Equals(schema, SchadensfresseRulesCanonicalJson.SchemaVersion, StringComparison.Ordinal) || !string.Equals(hash, SchadensfresseRulesCanonicalJson.CanonicalSha256, StringComparison.Ordinal)) throw new InvalidDataException("Typed context identity is not an exact schadensfresse rules-only profile."); }
    internal static void ValidateDocuments(IReadOnlyList<ResolvedTypedContextDocument> docs, int renderedBytes) { if (docs.Count != MaximumDocuments) throw new InvalidDataException("Rules-only typed context requires exactly one document."); ValidateDocument(docs[0]); if (renderedBytes < 0 || checked((renderedBytes + 3) / 4) > MaximumEstimatedRenderedContextTokens) throw new InvalidDataException("Rules-only rendered context exceeds the exact 2048-token budget."); }
    internal static void ValidateDocument(ResolvedTypedContextDocument? d) { if (d is null || !string.Equals(d.Kind, RulesDocumentKind, StringComparison.Ordinal) || !string.Equals(d.Name, RulesDocumentName, StringComparison.Ordinal) || d.Version < 0 || !TypedContextCanonicalJson.IsLowercaseSha256(d.ContentSha256)) throw new InvalidDataException("Typed context document is not the exact immutable schadensfresse rules document."); }
}

public static class TypedContextCanonicalJson
{
    public const string TimestampFormat = "yyyy-MM-dd'T'HH:mm:ss.fffffff'Z'"; public const int TimestampLength = 28;
    public static byte[] SerializeManifest(ResolvedTypedContextManifest m) { ArgumentNullException.ThrowIfNull(m); SchadensfresseTypedContextProfiles.ValidateManifestStructure(m, 0); return Write(w => { w.WriteStartObject(); Root(w, m.SeasonPartition, m.CommunityContext, m.BundesligaSeasonSubcompetition, m.ProfileId, m.RoutingSeedSha256, m.RulesObservedAt, m.RulesSchemaVersion, m.CanonicalRulesSha256); w.WritePropertyName("documents"); w.WriteStartArray(); Document(w, m.Documents[0]); w.WriteEndArray(); w.WriteEndObject(); }); }
    public static byte[] SerializeBinding(ResolvedTypedContextPublicationBinding b) { ArgumentNullException.ThrowIfNull(b); SchadensfresseTypedContextProfiles.ValidateBindingStructure(b); return Write(w => { w.WriteStartObject(); w.WriteString("seasonPartition", b.SeasonPartition); w.WriteString("communityContext", b.CommunityContext); w.WriteString("profileId", b.ProfileId); w.WriteString("routingSeedSha256", b.RoutingSeedSha256); w.WriteString("bundesligaSeasonSubcompetition", b.BundesligaSeasonSubcompetition.ToSerializedValue()); w.WriteString("rulesObservedAt", FormatTimestamp(b.RulesObservedAt)); w.WriteString("rulesSchemaVersion", b.RulesSchemaVersion); w.WriteString("canonicalRulesSha256", b.CanonicalRulesSha256); w.WritePropertyName("document"); Document(w, b.Document); w.WriteEndObject(); }); }
    public static ResolvedTypedContextManifest DeserializeManifest(ReadOnlySpan<byte> bytes) { Input(bytes); try { using var json = JsonDocument.Parse(bytes.ToArray()); var r = json.RootElement; Props(r, "seasonPartition", "communityContext", "bundesligaSeasonSubcompetition", "profileId", "routingSeedSha256", "rulesObservedAt", "rulesSchemaVersion", "canonicalRulesSha256", "documents"); var docs = r.GetProperty("documents"); if (docs.ValueKind != JsonValueKind.Array || docs.GetArrayLength() != 1) throw new InvalidDataException("documents must contain exactly one document."); var m = new ResolvedTypedContextManifest(String(r, "seasonPartition"), String(r, "communityContext"), Sub(r), String(r, "profileId"), String(r, "routingSeedSha256"), Time(r, "rulesObservedAt"), String(r, "rulesSchemaVersion"), String(r, "canonicalRulesSha256"), [ParseDocument(docs[0])]); SchadensfresseTypedContextProfiles.ValidateManifestStructure(m, 0); Canonical(bytes, SerializeManifest(m)); return m; } catch (JsonException ex) { throw new InvalidDataException("Typed context manifest JSON is invalid.", ex); } }
    public static ResolvedTypedContextPublicationBinding DeserializeBinding(ReadOnlySpan<byte> bytes) { Input(bytes); try { using var json = JsonDocument.Parse(bytes.ToArray()); var r = json.RootElement; Props(r, "seasonPartition", "communityContext", "profileId", "routingSeedSha256", "bundesligaSeasonSubcompetition", "rulesObservedAt", "rulesSchemaVersion", "canonicalRulesSha256", "document"); var b = new ResolvedTypedContextPublicationBinding(String(r, "seasonPartition"), String(r, "communityContext"), String(r, "profileId"), String(r, "routingSeedSha256"), Sub(r), Time(r, "rulesObservedAt"), String(r, "rulesSchemaVersion"), String(r, "canonicalRulesSha256"), ParseDocument(r.GetProperty("document"))); SchadensfresseTypedContextProfiles.ValidateBindingStructure(b); Canonical(bytes, SerializeBinding(b)); return b; } catch (JsonException ex) { throw new InvalidDataException("Typed context binding JSON is invalid.", ex); } }
    public static byte[] SerializeBindingKeyTuple(ResolvedTypedContextPublicationBindingKey k) { ArgumentNullException.ThrowIfNull(k); if (string.IsNullOrEmpty(k.SeasonPartition) || string.IsNullOrEmpty(k.CommunityContext) || string.IsNullOrEmpty(k.ProfileId) || !IsLowercaseSha256(k.RoutingSeedSha256)) throw new InvalidDataException("Typed context binding key is invalid."); return JsonSerializer.SerializeToUtf8Bytes(new[] { k.SeasonPartition, k.CommunityContext, k.ProfileId, k.RoutingSeedSha256 }); }
    public static string CreatePhysicalBindingId(ResolvedTypedContextPublicationBindingKey key) => Convert.ToBase64String(SerializeBindingKeyTuple(key)).TrimEnd('=').Replace('+', '-').Replace('/', '_');
    public static ResolvedTypedContextPublicationBindingKey DeserializePhysicalBindingId(string id) { ArgumentException.ThrowIfNullOrEmpty(id); if (id.Contains('=') || id.Any(c => !(char.IsAsciiLetterOrDigit(c) || c is '-' or '_'))) throw new InvalidDataException("Binding physical ID is not unpadded base64url."); byte[] bytes; try { var b = id.Replace('-', '+').Replace('_', '/'); bytes = Convert.FromBase64String(b.PadRight(b.Length + ((4 - b.Length % 4) % 4), '=')); } catch (FormatException ex) { throw new InvalidDataException("Binding physical ID is not valid base64url.", ex); } try { using var json = JsonDocument.Parse(bytes); var a = json.RootElement; if (a.ValueKind != JsonValueKind.Array || a.GetArrayLength() != 4 || a.EnumerateArray().Any(x => x.ValueKind != JsonValueKind.String || string.IsNullOrEmpty(x.GetString()))) throw new InvalidDataException("Binding physical ID does not contain a complete string tuple."); var v = a.EnumerateArray().Select(x => x.GetString()!).ToArray(); var k = new ResolvedTypedContextPublicationBindingKey(v[0], v[1], v[2], v[3]); if (!bytes.SequenceEqual(SerializeBindingKeyTuple(k)) || !string.Equals(id, CreatePhysicalBindingId(k), StringComparison.Ordinal)) throw new InvalidDataException("Binding physical ID does not encode the canonical tuple."); return k; } catch (JsonException ex) { throw new InvalidDataException("Binding physical ID tuple JSON is invalid.", ex); } }
    public static string FormatTimestamp(DateTimeOffset value) => value.ToUniversalTime().ToString(TimestampFormat, System.Globalization.CultureInfo.InvariantCulture);
    public static bool IsLowercaseSha256(string? v) => v is { Length: 64 } && v.All(c => c is >= '0' and <= '9' or >= 'a' and <= 'f');
    public static void ValidateFreshObservation(DateTimeOffset observation, DateTimeOffset evaluation) { observation = observation.ToUniversalTime(); evaluation = evaluation.ToUniversalTime(); if (observation > evaluation || evaluation - observation > TimeSpan.FromHours(24)) throw new InvalidDataException("Rules observation is future-dated or older than 24 hours."); }
    private static byte[] Write(Action<Utf8JsonWriter> action) { using var stream = new MemoryStream(); using (var w = new Utf8JsonWriter(stream, new JsonWriterOptions { Indented = false, Encoder = System.Text.Encodings.Web.JavaScriptEncoder.Default })) action(w); return stream.ToArray(); }
    private static void Root(Utf8JsonWriter w, string season, string community, BundesligaSeasonSubcompetition sub, string profile, string seed, DateTimeOffset observed, string schema, string hash) { w.WriteString("seasonPartition", season); w.WriteString("communityContext", community); w.WriteString("bundesligaSeasonSubcompetition", sub.ToSerializedValue()); w.WriteString("profileId", profile); w.WriteString("routingSeedSha256", seed); w.WriteString("rulesObservedAt", FormatTimestamp(observed)); w.WriteString("rulesSchemaVersion", schema); w.WriteString("canonicalRulesSha256", hash); }
    private static void Document(Utf8JsonWriter w, ResolvedTypedContextDocument d) { w.WriteStartObject(); w.WriteString("kind", d.Kind); w.WriteString("name", d.Name); w.WriteNumber("version", d.Version); w.WriteString("contentSha256", d.ContentSha256); w.WriteEndObject(); }
    private static void Input(ReadOnlySpan<byte> bytes) { if (bytes.IsEmpty || bytes[0] == 0xEF || bytes[0] is (byte)' ' or (byte)'\t' or (byte)'\r' or (byte)'\n' || bytes[^1] is (byte)' ' or (byte)'\t' or (byte)'\r' or (byte)'\n') throw new InvalidDataException("Typed context JSON must be canonical UTF-8 without BOM or whitespace."); }
    private static void Canonical(ReadOnlySpan<byte> b, byte[] c) { if (!b.SequenceEqual(c)) throw new InvalidDataException("Typed context JSON is not byte-for-byte canonical."); }
    private static void Props(JsonElement e, params string[] expected) { if (e.ValueKind != JsonValueKind.Object) throw new InvalidDataException("Expected JSON object."); if (!e.EnumerateObject().Select(x => x.Name).SequenceEqual(expected, StringComparer.Ordinal)) throw new InvalidDataException("JSON properties are missing, duplicate, unknown, or out of canonical order."); }
    private static string String(JsonElement r, string n) { var v = r.GetProperty(n); return v.ValueKind == JsonValueKind.String && !string.IsNullOrEmpty(v.GetString()) ? v.GetString()! : throw new InvalidDataException($"{n} must be a nonempty string."); }
    private static BundesligaSeasonSubcompetition Sub(JsonElement r) { var v = String(r, "bundesligaSeasonSubcompetition"); return BundesligaSeasonRoutingIdentityValues.TryParseBundesligaSeasonSubcompetition(v, out var p) ? p : throw new InvalidDataException("Unknown subcompetition."); }
    private static ResolvedTypedContextDocument ParseDocument(JsonElement e) { Props(e, "kind", "name", "version", "contentSha256"); var v = e.GetProperty("version"); if (v.ValueKind != JsonValueKind.Number || !v.TryGetInt32(out var i)) throw new InvalidDataException("Document version must be an Int32."); return new ResolvedTypedContextDocument(String(e, "kind"), String(e, "name"), i, String(e, "contentSha256")); }
    private static DateTimeOffset Time(JsonElement r, string n) { var v = String(r, n); if (v.Length != TimestampLength || v.Any(c => c > 0x7f) || !DateTimeOffset.TryParseExact(v, TimestampFormat, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.AssumeUniversal | System.Globalization.DateTimeStyles.AdjustToUniversal, out var p) || !string.Equals(FormatTimestamp(p), v, StringComparison.Ordinal)) throw new InvalidDataException("Timestamp must be exact canonical UTC text."); return p; }
}

public static class ResolvedTypedContextPublicationBindingContract
{
    public static TypedContextPublicationBindingUpsertResult SelectEffective(ResolvedTypedContextPublicationBinding? current, ResolvedTypedContextPublicationBinding candidate, DateTimeOffset at) { ArgumentNullException.ThrowIfNull(candidate); SchadensfresseTypedContextProfiles.ValidateBindingStructure(candidate); SchadensfresseTypedContextProfiles.ValidateBindingFreshness(candidate, at); if (current is null) return TypedContextPublicationBindingUpsertResult.Created(candidate); SchadensfresseTypedContextProfiles.ValidateBindingStructure(current); if (current.RulesObservedAt.ToUniversalTime() > at.ToUniversalTime()) throw new InvalidDataException("Stored binding is future-dated and corrupt."); if (current.Key != candidate.Key || !IdentityEquals(current, candidate)) return TypedContextPublicationBindingUpsertResult.Drift(current); return candidate.RulesObservedAt > current.RulesObservedAt ? TypedContextPublicationBindingUpsertResult.Updated(candidate) : TypedContextPublicationBindingUpsertResult.NoOp(current); }
    public static void ValidateExactReadback(ResolvedTypedContextPublicationBindingKey requested, ResolvedTypedContextPublicationBinding expectedEffective, ResolvedTypedContextPublicationBinding? returned, DateTimeOffset readbackEvaluationInstant) { ArgumentNullException.ThrowIfNull(requested); ArgumentNullException.ThrowIfNull(expectedEffective); ArgumentNullException.ThrowIfNull(returned); SchadensfresseTypedContextProfiles.ValidateBindingStructure(expectedEffective); SchadensfresseTypedContextProfiles.ValidateBindingStructure(returned); if (returned.Key != requested || !IdentityEquals(returned, expectedEffective) || returned.RulesObservedAt < expectedEffective.RulesObservedAt) throw new InvalidDataException("Exact binding readback does not match the requested key and effective identity."); SchadensfresseTypedContextProfiles.ValidateBindingFreshness(returned, readbackEvaluationInstant); }
    public static bool IdentityEquals(ResolvedTypedContextPublicationBinding x, ResolvedTypedContextPublicationBinding y) => x.Key == y.Key && x.BundesligaSeasonSubcompetition == y.BundesligaSeasonSubcompetition && string.Equals(x.RulesSchemaVersion, y.RulesSchemaVersion, StringComparison.Ordinal) && string.Equals(x.CanonicalRulesSha256, y.CanonicalRulesSha256, StringComparison.Ordinal) && x.Document.Equals(y.Document);
}
public enum TypedContextPublicationBindingUpsertDisposition { Created, Updated, NoOp, IdentityDrift }
public sealed record TypedContextPublicationBindingUpsertResult(TypedContextPublicationBindingUpsertDisposition Disposition, ResolvedTypedContextPublicationBinding EffectiveBinding) { public bool Succeeded => Disposition != TypedContextPublicationBindingUpsertDisposition.IdentityDrift; public static TypedContextPublicationBindingUpsertResult Created(ResolvedTypedContextPublicationBinding b) => new(TypedContextPublicationBindingUpsertDisposition.Created, b); public static TypedContextPublicationBindingUpsertResult Updated(ResolvedTypedContextPublicationBinding b) => new(TypedContextPublicationBindingUpsertDisposition.Updated, b); public static TypedContextPublicationBindingUpsertResult NoOp(ResolvedTypedContextPublicationBinding b) => new(TypedContextPublicationBindingUpsertDisposition.NoOp, b); public static TypedContextPublicationBindingUpsertResult Drift(ResolvedTypedContextPublicationBinding b) => new(TypedContextPublicationBindingUpsertDisposition.IdentityDrift, b); }
public interface IResolvedTypedContextPublicationBindingRepository { Task<ResolvedTypedContextPublicationBinding?> GetExactAsync(ResolvedTypedContextPublicationBindingKey key, CancellationToken cancellationToken = default); Task<TypedContextPublicationBindingUpsertResult> UpsertExactAsync(ResolvedTypedContextPublicationBinding candidate, CancellationToken cancellationToken = default); }
