name: ehonda-ai-arena ⚽ o3 ⚽ Matchday

on:
  # Schedule to run twice daily one hour after context collection
  # Note: GitHub Actions cron runs in UTC only, so these times approximate Europe/Berlin
  schedule:
    - cron: '0 1 * * *'    # ~02:00 AM Europe/Berlin (01:00 UTC = 02:00 CET, 03:00 CEST) - 1 hour after context collection
    - cron: '0 13 * * *'   # ~02:00 PM Europe/Berlin (13:00 UTC = 14:00 CET, 15:00 CEST) - 1 hour after context collection
  
  # Allow manual triggering
  # Note: No force_prediction or max_repredictions inputs since this workflow
  # copies predictions from pes-squad (same model, runs earlier) - no reprediction needed
  workflow_dispatch:

jobs:
  call-base-workflow:
    name: Run Matchday Predictions
    uses: ./.github/workflows/base-matchday-predictions.yml
    with:
      community: "ehonda-ai-arena"
      model: "o3"
      community_context: "pes-squad"
      trigger_type: ${{ github.event_name == 'schedule' && 'scheduled' || 'manual' }}
      force_prediction: false
      max_repredictions: 0
    secrets:
      kicktipp_username: ${{ secrets.EHONDA_AI_ARENA_O3_KICKTIPP_USERNAME }}
      kicktipp_password: ${{ secrets.EHONDA_AI_ARENA_O3_KICKTIPP_PASSWORD }}
      firebase_project_id: ${{ secrets.FIREBASE_PROJECT_ID }}
      firebase_service_account_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
      openai_api_key: ${{ secrets.OPENAI_API_KEY }}
