name: Ehonda AI Arena - Matchday Predictions

on:
  # Custom schedule for AI Arena - different timing than test-buli
  schedule:
    - cron: '30 6 * * *'   # 6:30 AM Europe/Berlin (6:30 UTC = 7:30 CET / 8:30 CEST) 
    - cron: '30 18 * * *'  # 6:30 PM Europe/Berlin (18:30 UTC = 19:30 CET / 20:30 CEST)
  
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      force_prediction:
        description: 'Force prediction even if verify passes'
        required: false
        default: false
        type: boolean

jobs:
  call-base-workflow:
    name: Run Matchday Predictions
    uses: ./.github/workflows/base-matchday-predictions.yml
    with:
      community: "ehonda-ai-arena"
      model: "o1"
      community_context: "pes-squad"
      trigger_type: ${{ github.event_name == 'schedule' && 'scheduled' || 'manual' }}
      force_prediction: ${{ github.event.inputs.force_prediction == 'true' }}
    secrets:
      kicktipp_username: ${{ secrets.EHONDA_AI_ARENA_KICKTIPP_USERNAME }}
      kicktipp_password: ${{ secrets.EHONDA_AI_ARENA_KICKTIPP_PASSWORD }}
      firebase_project_id: ${{ secrets.FIREBASE_PROJECT_ID }}
      firebase_service_account_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
      openai_api_key: ${{ secrets.OPENAI_API_KEY }}
