name: Ehonda AI Arena - Bonus Predictions

on:
  # Custom schedule for AI Arena - once weekly on Sunday evening
  schedule:
    - cron: '0 20 * * SUN'  # 8 PM Sunday Europe/Berlin (20:00 UTC = 21:00 CET / 22:00 CEST)
  
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      model:
        description: 'OpenAI model to use for predictions'
        required: true
        default: 'o1'
        type: choice
        options:
          - 'o4-mini'
          - 'o1'
      force_prediction:
        description: 'Force prediction even if verify passes'
        required: false
        default: false
        type: boolean

jobs:
  call-base-workflow:
    name: Run Bonus Predictions
    uses: ./.github/workflows/base-bonus-predictions.yml
    with:
      # Community configuration for ehonda-ai-arena
      community_config: |
        {
          "community": "ehonda-ai-arena",
          "predictions": {
            "matches": {
              "model": "o1",
              "community-context": "pes-squad"
            },
            "bonus": {
              "community-context": "pes-squad",
              "model": "o1"
            }
          }
        }
      trigger_type: ${{ github.event_name == 'schedule' && 'scheduled' || 'manual' }}
      force_prediction: ${{ github.event.inputs.force_prediction == 'true' }}
      model_override: ${{ github.event.inputs.model || '' }}
    secrets:
      kicktipp_username: ${{ secrets.EHONDA_AI_ARENA_KICKTIPP_USERNAME }}
      kicktipp_password: ${{ secrets.EHONDA_AI_ARENA_KICKTIPP_PASSWORD }}
      firebase_project_id: ${{ secrets.FIREBASE_PROJECT_ID }}
      firebase_service_account_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
      openai_api_key: ${{ secrets.OPENAI_API_KEY }}
