name: ehonda-ai-arena ⚽ gpt-5-nano ⚽ Matchday

on:
  # Schedule to run twice daily 30 minutes after context collection
  # Note: GitHub Actions cron runs in UTC only, so these times approximate Europe/Berlin
  schedule:
    - cron: '30 0 * * *'   # ~01:30 AM Europe/Berlin (00:30 UTC = 01:30 CET, 02:30 CEST) - 30 min after context collection
    - cron: '30 12 * * *'  # ~01:30 PM Europe/Berlin (12:30 UTC = 13:30 CET, 14:30 CEST) - 30 min after context collection
  
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      force_prediction:
        description: 'Force prediction even if verify passes'
        required: false
        default: false
        type: boolean

jobs:
  call-base-workflow:
    name: Run Matchday Predictions
    uses: ./.github/workflows/base-matchday-predictions.yml
    with:
      community: "ehonda-ai-arena"
      model: "gpt-5-nano"
      community_context: "pes-squad"
      trigger_type: ${{ github.event_name == 'schedule' && 'scheduled' || 'manual' }}
      force_prediction: ${{ github.event.inputs.force_prediction == 'true' }}
    secrets:
      kicktipp_username: ${{ secrets.EHONDA_AI_ARENA_GPT_5_NANO_KICKTIPP_USERNAME }}
      kicktipp_password: ${{ secrets.EHONDA_AI_ARENA_GPT_5_NANO_KICKTIPP_PASSWORD }}
      firebase_project_id: ${{ secrets.FIREBASE_PROJECT_ID }}
      firebase_service_account_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
      openai_api_key: ${{ secrets.OPENAI_API_KEY }}
